### ISSUE TITLE
Problems with passport data script

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/subsets_genebank_accessions#48]
Hi everyone. 
This issue were created because when I run the script to get the accessions data from a crop in some cases the script generates a issue (in the image attached). The cases generates the issue are those cases I put like input the crops are in the crop table in the issue #40  in the column "Stored in the database" with value "Processing"

![image](https://user-images.githubusercontent.com/36042734/115048421-29034180-9e9f-11eb-9aa3-e2fd6edfe1ac.png)

Thanks so much

Regards.

**Comment by khadijaAouzal** [comment]
@juangarc I got the error just for **Coconut** and **Coffee**. The reason is that all their coordinates have NA values and therefore the geo columns (latitude and longitude) are not retrieved.

For the other crops, I extracted the passport data without any error. Could you show me the error you get when trying to extract their accessions?

**Comment by juangarc** [comment]
> @juangarc I got the error just for **Coconut** and **Coffee**. The reason is that all their coordinates have NA values and therefore the geo columns (latitude and longitude) are not retrieved.
> 
> For the other crops, I extracted the passport data without any error. Could you show me the error you get when trying to extract their accessions?

@khadijaAouzal  This is the issue with any crop has a "Processing" status in our table:

Faba bean

![image](https://user-images.githubusercontent.com/36042734/115555032-b1edf480-a274-11eb-8471-536528eb94e4.png)

**Comment by khadijaAouzal** [comment]
@juangarc here the problem is due to the crop name. There shouldn't be a space. 

To get accessions, you should use the short names of the crops:

name | short name
-- | --
African yam bean | africanyambean
Amaranth | amaranth
Andean root and tuber crops | artc
Apple | apple
Bambara groundnut | bambara
Banana | banana
Barley | barley
Barnyard millet | barnyardmillet
Beans | beans
Breadfruit | breadfruit
Carrot | carrot
Cassava | cassava
Chickpea | chickpea
Coconut | coconut
Coffee | coffee
Cowage | cowage
Cowpea | cowpea
Eggplant | eggplant
Faba bean | fababean
Finger millet | fingermillet
Forages | forages
Foxtail millet | foxtailmillet
Grasspea | grasspea
Groundnut | groundnuts
Kodo millet | kodomillet
Lentil | lentil
Lettuce | lettuce
Little millet | littlemillet
Maize | maize
Oat | oat
Pea | pea
Pearl millet | pearlmillet
Pigeonpea | pigeonpea
Potato | potato
Proso millet | prosomillet
Rice | rice
Rye | rye
Sapota | sapota
Sesame | sesame
Sorghum | sorghum
Soybean | soybeans
Squashes | squashes
Sunflower | sunflower
Sweetpotato | sweetpotato
Taro | taro
Tea | tea
Tomato | tomato
Wheat | wheat
Yam | yam

**Comment by juangarc** [comment]
Thanks @khadijaAouzal  I could fix the issue.
